# Generated by Django 5.1.1 on 2024-09-05 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Marca')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Fornecedor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome do produto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('serial_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de serie')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço de custo')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Prelo de venda')),
                ('quantily', models.IntegerField(verbose_name='Quantidade em estoque')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='imagens')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='sge.category', verbose_name='Categoria')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand', to='sge.brand', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Outflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantily', models.IntegerField(verbose_name='Quantidade')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_outflow', to='sge.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantily', models.IntegerField(verbose_name='Quantidade')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_inflow', to='sge.product', verbose_name='Produto')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suplier', to='sge.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-created_at'],
            },
        ),
    ]
