# Generated by Django 5.1.1 on 2024-09-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantily',
            field=models.IntegerField(default=0, verbose_name='Quantidade em estoque'),
        ),
    ]
