# Generated by Django 5.1.1 on 2024-09-16 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sge', '0002_alter_product_quantily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inflow', to='sge.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplier', to='sge.supplier', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_outflow', to='sge.product', verbose_name='Produto'),
        ),
    ]
